name: simplebank-test

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d simple_bank"]
      interval: 2s
      timeout: 3s
      retries: 10

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migration:/migrations
    command: ["-path", "/migrations", "-database", "postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable", "-verbose", "up"]
    depends_on:
      postgres:
        condition: service_healthy

  test:
    image: golang:1.24-alpine3.21
    working_dir: /app
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    command: ["go", "test", "-v", "-cover", "-short", "./..."]
    depends_on:
      migrate:
        condition: service_completed_successfully

volumes:
  go-mod-cache:
  go-build-cache:
